[package]
name = "bevy-mon-proto"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
bevy = {version = "0.18.1", features = ["dynamic_linking"]}
ron = "0.12.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
bevy_spine = { git = "https://github.com/jabuwu/bevy_spine", branch = "main", features = ["ui"] }
bevy_egui = "0.39.1"
bevy_framepace = "0.21.0"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
